# Generated by Django 5.2.8 on 2025-11-23 05:11

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Ubicacion',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=100, verbose_name='Nombre del Lugar')),
                ('descripcion', models.TextField(verbose_name='Descripción / Qué hay aquí')),
                ('como_llegar', models.TextField(blank=True, verbose_name='Ruta / Cómo llegar')),
                ('pos_x', models.IntegerField(default=50, help_text='Posición Horizontal (0 a 100%)')),
                ('pos_y', models.IntegerField(default=50, help_text='Posición Vertical (0 a 100%)')),
                ('color', models.CharField(default='#d32f2f', help_text='Ej: #d32f2f (rojo), #1976d2 (azul)', max_length=20)),
            ],
            options={
                'verbose_name': 'Ubicación del Mapa',
                'verbose_name_plural': 'Ubicaciones del Mapa',
            },
        ),
    ]
